version: "3.8"
services:
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - backend-sync:/app:nocopy
      - bundles:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    command: bash -c "yarn run serve"
    volumes:
      - frontend-sync:/app:nocopy
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"

volumes:
  bundles:
  node_modules:
  backend-sync:
    external: true
  frontend-sync:
    external: true
